#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Test Runner

on:
  repository_dispatch:
  workflow_dispatch:
#  watch:
#    types: started

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-18.06-k5.4

jobs:
  First-Job:
    runs-on: test-runner

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Clone Source Code
        id: clone
        run: |
          df -hT $PWD
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH

  Second-Job:
    needs: [First-Job]
    runs-on: test-runner

    steps:
      - name: List Folder Content
        id: init
        run: |
          ls -al